name: grid_6x6_drop20
net_file: sumo_rl/nets/generated/grid_6x6_drop20/grid_6x6_drop20.net.xml
route_file: sumo_rl/nets/generated/grid_6x6_drop20/grid_6x6_drop20.rou.xml

delta_time: 5
num_seconds: 3600
sumo_seed: 42

max_lanes: 16
max_queue: 50.0
max_wait: 300.0
max_speed: 50.0

k_max: 8
max_hops: 3

use_libsumo: true
begin_time: 0.0
