name: city_6
net_file: sumo_rl/nets/RESCO/ingolstadt7/ingolstadt7.net.xml
route_file: sumo_rl/nets/RESCO/ingolstadt7/ingolstadt7.rou_shifted.xml
delta_time: 5
num_seconds: 3600
sumo_seed: 42
max_lanes: 16
max_queue: 50.0
max_wait: 500.0
max_speed: 50.0
k_max: 8
max_hops: 3
use_libsumo: true
begin_time: 0.0
