from typing import Dict, List, Optional, Tuple, Any
import random
import logging
import math
from collections import Counter, deque

import numpy as np

logger = logging.getLogger(__name__)


try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from agents.networks import NeighborAttentionQNetwork

    TORCH_AVAILABLE = True
except Exception:
    TORCH_AVAILABLE = False


Observation = Dict[str, np.ndarray]
# Expected keys: "own", "neighbors", "neighbor_mask", "hop_dist", "action_mask"


class ReplayBuffer:
    """Stores structured (dict) observations from ALL intersections of a
    city, pooled together. Pooling across intersections -- rather than one
    buffer per intersection -- is what forces the shared network to learn a
    genuinely topology-agnostic policy instead of overfitting to one
    intersection's quirks.
    """

    def __init__(self, capacity: int = 10000):
        self.buffer = deque(maxlen=capacity)

    def add(self, obs: Observation, action: int, reward: float, next_obs: Observation, done: bool,
            n: int = 1):
        """``n`` = number of environment steps this transition's ``reward``
        already spans (n-step returns, see DQNAgent's ``n_step``). Defaults
        to 1 (plain 1-step TD), which is byte-for-byte what every caller
        used before n-step support was added -- ``optimize()`` uses
        ``gamma**n`` as the bootstrap discount, and ``gamma**1 == gamma``
        exactly, so n_step=1 (the default) is a true no-op."""
        self.buffer.append((obs, int(action), float(reward), next_obs, float(done), int(n)))

    def clear(self) -> None:
        """Drop every stored transition. Used by the replay-buffer-reset-
        on-detected-lock-in lever (fidings sec 78/item 20): once a
        confident lock-in is detected, the buffer is dominated by
        transitions generated by that same locked policy -- a closed
        feedback loop where TD-bootstrapping off increasingly homogeneous
        data can perpetuate the lock. Clearing forces fresh, more diverse
        experience before the next round of training."""
        self.buffer.clear()

    def sample(self, batch_size: int):
        batch = random.sample(self.buffer, min(batch_size, len(self.buffer)))
        obs, actions, rewards, next_obs, dones, ns = zip(*batch)
        return obs, actions, rewards, next_obs, dones, ns

    def __len__(self):
        return len(self.buffer)


def _collate(obs_list, device):
    """Batch a list of observation dicts into tensors."""
    own = torch.tensor(
        np.array([o["own"] for o in obs_list]), dtype=torch.float32, device=device
    )
    neighbors = torch.tensor(
        np.array([o["neighbors"] for o in obs_list]), dtype=torch.float32, device=device
    )
    neighbor_mask = torch.tensor(
        np.array([o["neighbor_mask"] for o in obs_list]), dtype=torch.float32, device=device
    )
    hop_dist = torch.tensor(
        np.array([
            o.get("hop_dist", np.zeros(o["neighbors"].shape[0], dtype=np.int64))
            for o in obs_list
        ]),
        dtype=torch.long,
        device=device,
    )
    action_mask = torch.tensor(
        np.array([o["action_mask"] for o in obs_list]), dtype=torch.float32, device=device
    )
    return own, neighbors, neighbor_mask, hop_dist, action_mask


def _mask_q(q: "torch.Tensor", action_mask: "torch.Tensor") -> "torch.Tensor":
    """Set Q-values of invalid actions to -inf so argmax / target
    computation never picks or bootstraps off an action that doesn't
    exist for this intersection's topology."""
    neg_inf = torch.finfo(q.dtype).min
    return q.masked_fill(action_mask < 0.5, neg_inf)


class DQNAgent:
    """Torch-based DQN agent with a shared, topology-agnostic Q-network.

    One instance of this agent is trained against every intersection in a
    city simultaneously (see ``train``): the same weights are used to act
    for every ``ts_id`` each tick, and every intersection's transitions are
    stored in the same replay buffer. This is what makes it a "foundation
    model" for intersections rather than N separate per-intersection
    models.
    """

    def __init__(
        self,
        own_dim: int = 4,
        neighbor_dim: int = 3,
        action_dim: int = 2,
        k_max: int = 8,
        lr: float = 1e-3,
        device: str = "cpu",
        buffer_size: int = 50000,
        batch_size: int = 64,
        gamma: float = 0.99,
        target_update: int = 200,
        d_model: int = 128,
        n_heads: int = 4,
        n_hops: int = 4,
        reward_clip: Optional[float] = 10.0,
        eps_decay: float = 20000.0,
        lr_decay: float = 1.0,
        min_lr: float = 1e-6,
        head_fix: bool = True,
        tau: float = 0.005,
        mu: float = 0.0,
        dueling: bool = False,
        n_step: int = 1,
        init_steps_done: int = 0,
        q_entropy_weight: float = 0.0,
        use_batchnorm: bool = False,
        activation: str = "relu",
        encoder_depth: int = 2,
        n_attn_layers: int = 1,
        recurrent: bool = False,
        topology_conditioned: bool = False,
        anchor_revert: bool = False,
        anchor_warmup_calls: int = 100,
        anchor_check_every: int = 50,
        anchor_qgap_growth_threshold: float = 3.0,
        anchor_pullback_beta: float = 0.5,
    ):
        self.own_dim = own_dim
        self.neighbor_dim = neighbor_dim
        self.action_dim = action_dim
        self.k_max = k_max
        self.device = torch.device(device)

        net_kwargs = dict(
            own_dim=own_dim,
            neighbor_dim=neighbor_dim,
            action_dim=action_dim,
            k_max=k_max,
            d_model=d_model,
            n_heads=n_heads,
            n_hops=n_hops,
            head_fix=head_fix,
            dueling=dueling,
            use_batchnorm=use_batchnorm,
            activation=activation,
            encoder_depth=encoder_depth,
            n_attn_layers=n_attn_layers,
            recurrent=recurrent,
            topology_conditioned=topology_conditioned,
        )
        self.q = NeighborAttentionQNetwork(**net_kwargs).to(self.device)
        self.q_target = NeighborAttentionQNetwork(**net_kwargs).to(self.device)
        self.q_target.load_state_dict(self.q.state_dict())
        # q_target is never trained by backprop (only Polyak/hard-synced
        # from self.q), so it always runs in eval mode -- this also sides
        # steps a real subtlety with BatchNorm specifically: Polyak
        # averaging below only touches .parameters() (weight/bias), not
        # BatchNorm's running_mean/running_var buffers, so q_target's BN
        # statistics only ever get updated by the hard copies here and in
        # load_state_dict()/optimize()'s hard-copy branch, not by the
        # per-step Polyak loop. Deliberate simplification, not a bug: with
        # use_batchnorm=False (the default) this comment is moot.
        self.q_target.eval()

        # AdamW, not Adam: plain torch.optim.Adam folds weight_decay into the
        # gradient before the moment estimates, so a parameter that gets
        # ~zero true gradient (e.g. a masked-out Q-head row for an action a
        # low-action-count city never takes) still gets a "gradient" of
        # weight_decay*param every step. Once Adam's running estimates lock
        # onto that as a near-constant signal, the normalized update
        # collapses to essentially -lr*sign(param) -- decaying that weight
        # at a rate set by the LEARNING RATE, not by the (tiny) weight_decay
        # coefficient. Over the hundreds of optimizer steps in one local
        # round this silently erases untouched action rows/features.
        # AdamW applies weight_decay as a separate, decoupled term
        # (param -= lr*weight_decay*param), which behaves like the mild
        # regularizer weight_decay=1e-5 was actually meant to be.
        self.optimizer = optim.AdamW(self.q.parameters(), lr=lr, weight_decay=1e-5, eps=1e-6)
        self.lr_decay = lr_decay   # multiplicative decay applied once per federated round
        self.min_lr = min_lr
        self.replay = ReplayBuffer(buffer_size)
        self.batch_size = batch_size
        self.gamma = gamma
        self.eps_start = 1.0
        self.eps_end = 0.05
        self.eps_decay = eps_decay
        # Starts at 0 for a fresh agent; a resumed run passes the step count
        # the schedule would have reached by the resume round, so epsilon
        # picks up mid-decay instead of restarting at eps_start.
        self.steps_done = init_steps_done
        self.target_update = target_update
        self.tau = tau          # 0 = legacy hard copy; >0 = Polyak soft update every step
        self.learn_steps = 0
        # Reward clipping: applied when a transition is stored, not just
        # at optimize() time -- this is what actually stopped city_2's
        # loss blow-up (a few large-magnitude congestion rewards were
        # dominating the squared-error gradient). Set to None to disable.
        self.reward_clip = reward_clip
        # FedProx proximal term: penalizes local weights drifting from the
        # global weights this client started the round from, mu/2 *
        # ||w - w_global||^2 added directly to the training loss (see
        # optimize()). 0 = disabled, exactly recovers plain FedAvg local
        # training. The reference snapshot is taken in load_state_dict(),
        # which is called with the broadcast global weights at the start
        # of every federated round -- so "global" always means "what this
        # client received this round," not the very first round's weights.
        self.mu = mu
        if self.mu > 0:
            logger.warning(
                "FedProx proximal term is ENABLED (mu=%.4g). Swept 2026-08-06 across "
                "mu in {0.01, 0.03, 0.1} on the seed-4 divergence repro (both the 2-city "
                "and 3-city rosters) and found NO stabilizing effect at any value tested "
                "-- mu=0.1 was measurably worse on every metric (mean/best/worst reward). "
                "See fidings/divergence_investigation.md sec 14 before trusting this run's "
                "results as evidence the proximal term helps.",
                self.mu,
            )
        self._global_params: Optional[List["torch.Tensor"]] = None
        # n-step returns: instead of bootstrapping off a 1-step TD target,
        # accumulate n consecutive (clipped) rewards per intersection before
        # pushing a transition, and bootstrap with gamma**n instead of
        # gamma. 1 = disabled (default) -- every transition stored has n=1,
        # and gamma**1 == gamma exactly, so this is a true no-op, not just a
        # numerically-small change. See train()/_flush_nstep() for the
        # per-intersection accumulation (each intersection needs its own
        # sliding window since actions/rewards differ per ts_id).
        self.n_step = max(1, int(n_step))
        self._nstep_buffers: Dict[str, "deque"] = {}
        # Q-value entropy regularization: fidings/divergence_investigation.md
        # §53 found the network's rare good rounds are consistently the ones
        # with low Q-gap (i.e. high softmax(Q) entropy) -- confidently locked
        # bad policies have high Q-gap, and the one near-competent checkpoint
        # found anywhere in that document had a Q-gap 30-50x lower than its
        # neighbors. This subtracts entropy_weight * mean_batch_entropy from
        # the loss each optimize() step, i.e. rewards the online network for
        # keeping its Q-value distribution less peaked over valid actions,
        # instead of only ever encouraging uncertainty at eval time (§34/§36's
        # softmax-eval idea, which never touches training). 0 = disabled
        # (default, exact no-op -- optimize() skips the entropy term
        # entirely rather than just multiplying by zero).
        self.q_entropy_weight = float(q_entropy_weight)
        # Self-Anchoring Training with Confidence-Gated Reversion (bespoke design,
        # fidings/divergence_investigation.md's "genuinely new solution for our own
        # bottleneck" request): every mechanism tested against this project's
        # central retention/forgetting problem (recurrent memory, topology-
        # conditioning, Reptile-style blending, evolution strategies, sequential
        # curriculum training) shares one symptom -- a good policy is reachable but
        # not retained, matching §53's finding that the one good escape round ever
        # found had a Q-gap 30-50x lower than its confidently-locked neighbors. This
        # gives EACH ROUND's local training an active memory of how it started and a
        # cheap, already-validated signal (Q-gap growth, no extra forward pass or
        # holdout eval needed) to detect drift toward that exact lock-in pathology --
        # then partially pulls the weights back toward the round-start anchor rather
        # than letting local training degrade all the way to a confidently-wrong
        # policy before the next round's aggregation ever sees it. anchor_revert
        # defaults to False (exact no-op); the anchor itself is re-established fresh
        # at the start of every train() call (see train()'s own reset of
        # self._anchor_state below), not carried across rounds, so this doesn't
        # interact with anything cross-round (aggregation, --resume, etc.).
        self.anchor_revert = bool(anchor_revert)
        self.anchor_warmup_calls = int(anchor_warmup_calls)
        self.anchor_check_every = max(1, int(anchor_check_every))
        self.anchor_qgap_growth_threshold = float(anchor_qgap_growth_threshold)
        self.anchor_pullback_beta = float(anchor_pullback_beta)
        self._anchor_state: Optional[Dict[str, "torch.Tensor"]] = None
        self._anchor_qgap_ema: Optional[float] = None
        self._recent_qgap_ema: Optional[float] = None
        self._anchor_optimize_calls = 0
        logger.info(
            "own_dim=%d neighbor_dim=%d action_dim=%d k_max=%d eps_decay=%.0f",
            self.own_dim, self.neighbor_dim, self.action_dim, self.k_max, self.eps_decay,
        )

    # ------------------------------------------------------------------
    # Action selection
    # ------------------------------------------------------------------

    @staticmethod
    def _valid_actions(action_mask: np.ndarray) -> np.ndarray:
        valid = np.nonzero(action_mask > 0.5)[0]
        return valid

    def _random_valid_action(self, action_mask: np.ndarray) -> int:
        """Uniformly random action among the valid ones (falls back to any
        action index if the mask is empty). Draws exactly one
        ``random.choice`` call, shared by every explore-branch call site so
        the RNG usage stays in one place."""
        valid = self._valid_actions(action_mask)
        if len(valid) == 0:
            valid = np.arange(self.action_dim)
        return int(random.choice(valid))

    def _current_epsilon(self) -> float:
        return self.eps_end + (self.eps_start - self.eps_end) * math.exp(
            -1.0 * self.steps_done / self.eps_decay
        )

    def current_epsilon(self) -> float:
        """Public read-only view of the current epsilon value."""
        return self._current_epsilon()

    def _greedy_action(self, obs: Observation) -> int:
        return self._greedy_action_batch([obs])[0]

    def _greedy_action_batch(self, obs_list: List[Observation]) -> List[int]:
        """Greedy (exploit) action for each observation, one batched forward
        pass covering however many observations are passed in (i.e.
        however many intersections a city actually has that tick, not a
        fixed constant) -- ``_greedy_action`` is just this called with a
        list of one.

        Ties are broken uniformly at random rather than always taking the
        lowest index. Early in training (or on a symmetric network where
        two actions are genuinely equivalent) Q-values for different
        actions can be numerically indistinguishable; ``argmax`` always
        resolves that to the lowest index, which silently produces a "the
        model always picks action 0" pattern that looks like a learned
        policy but is actually just tie-break bias. One ``np.random.choice``
        draw per observation, in list order -- same numpy-RNG call sequence
        a per-observation loop would produce, just with the network forward
        pass batched.
        """
        # eval(): inference-only forward pass, possibly batch-size-1 (a
        # single-intersection city, or _greedy_action's list-of-one) --
        # BatchNorm1d rejects batch size 1 in train mode (can't compute a
        # meaningful batch variance from one sample). No-op when
        # use_batchnorm=False. optimize() switches back to train() before
        # its own forward pass.
        self.q.eval()
        with torch.no_grad():
            own, neighbors, neighbor_mask, hop_dist, action_mask = _collate(obs_list, self.device)
            q = self.q(own, neighbors, neighbor_mask, hop_dist)
            q = _mask_q(q, action_mask)
            q_np = q.cpu().numpy()

        actions = []
        for row in q_np:
            max_q = np.max(row)
            tied = np.flatnonzero(np.isclose(row, max_q, atol=1e-4))
            actions.append(int(np.random.choice(tied)))
        return actions

    def act_batch(
        self,
        obs_dict: Dict[str, Observation],
        eps: Optional[float] = None,
        explore: bool = True,
    ) -> Dict[str, int]:
        """Batched, per-tick action selection across every intersection in
        ``obs_dict`` -- same explore-vs-greedy decision, independently per
        intersection, in the same iteration order, drawing from the same
        two RNG streams (``random`` for the explore coin-flip and the
        uniform choice among valid actions, ``np.random`` for greedy
        tie-breaking) that calling ``act()`` once per intersection would.
        The only thing that changes is that every greedy intersection's Q
        lookup this tick happens in one batched forward pass instead of
        one forward pass each.
        """
        if explore and eps is None:
            eps = self._current_epsilon()

        actions: Dict[str, int] = {}
        greedy_ts_ids: List[str] = []
        greedy_obs: List[Observation] = []

        for ts_id, obs in obs_dict.items():
            if explore and random.random() < eps:
                actions[ts_id] = self._random_valid_action(obs["action_mask"])
            else:
                greedy_ts_ids.append(ts_id)
                greedy_obs.append(obs)

        if greedy_obs:
            for ts_id, a in zip(greedy_ts_ids, self._greedy_action_batch(greedy_obs)):
                actions[ts_id] = a

        return actions

    def q_values(self, obs: Observation, ts_id: Optional[str] = None) -> np.ndarray:
        """Masked Q-values for a single observation (invalid actions are
        NaN, not -inf, so callers can distinguish 'invalid' from 'valid
        but low' when inspecting/logging). ``ts_id`` is accepted and
        ignored here (this network is stateless) -- it exists so callers
        like ``federated/evaluator.py`` can pass it uniformly to every
        agent type; ``RecurrentDQNAgent`` overrides this to actually use
        it as a per-intersection hidden-state key."""
        self.q.eval()  # single observation -- see _greedy_action_batch's comment
        with torch.no_grad():
            own, neighbors, neighbor_mask, hop_dist, action_mask = _collate([obs], self.device)
            q = self.q(own, neighbors, neighbor_mask, hop_dist).squeeze(0).cpu().numpy()
        mask = obs["action_mask"] > 0.5
        out = np.full_like(q, np.nan)
        out[mask] = q[mask]
        return out

    def _epsilon_action(self, obs: Observation, eps: float) -> int:
        # NOTE: steps_done is advanced once per environment TICK (see
        # `train()`), not once per intersection per tick. Incrementing it
        # here (per-intersection) would make epsilon decay N times faster
        # in a city with N intersections than in a single-intersection
        # city, which desyncs the exploration schedule across the very
        # cities that get FedAvg'd together every round.
        if random.random() < eps:
            return self._random_valid_action(obs["action_mask"])
        return self._greedy_action(obs)

    def act(self, obs: Observation, explore: bool = True, eps: Optional[float] = None,
            ts_id: Optional[str] = None) -> int:
        """``ts_id`` is accepted and ignored here (this agent is stateless
        across ticks) -- see ``q_values``'s docstring for why the parameter
        exists on this base-class signature at all."""
        if explore:
            eps = self._current_epsilon() if eps is None else eps
            return self._epsilon_action(obs, eps)
        return self._greedy_action(obs)

    def select_action(self, obs: Observation) -> int:
        return self.act(obs, explore=True)

    # ------------------------------------------------------------------
    # Replay + optimization
    # ------------------------------------------------------------------

    def remember(self, obs: Observation, action: int, reward: float, next_obs: Observation, done: bool,
                 n: int = 1) -> None:
        if self.reward_clip is not None:
            reward = float(np.clip(reward, -self.reward_clip, self.reward_clip))
        self.replay.add(obs, action, reward, next_obs, done, n)

    def _clip_reward(self, r: float) -> float:
        if self.reward_clip is not None:
            return float(np.clip(r, -self.reward_clip, self.reward_clip))
        return r

    def _remember_step(self, ts_id: str, obs: Observation, action: int, reward: float,
                        next_obs: Observation, done: bool) -> None:
        """Per-intersection dispatch used by ``train()``'s tick loop: plain
        1-step ``remember()`` when ``n_step<=1`` (the default, unchanged
        behavior), or push into that intersection's n-step sliding-window
        accumulator otherwise. Each intersection gets its own window since
        actions/rewards differ per ``ts_id`` even though they share one
        pooled replay buffer (see ReplayBuffer's docstring)."""
        if self.n_step <= 1:
            self.remember(obs, action, reward, next_obs, done)
            return
        r = self._clip_reward(reward)
        buf = self._nstep_buffers.setdefault(ts_id, deque())
        buf.append((obs, action, r))
        if len(buf) >= self.n_step:
            self._flush_nstep(buf, next_obs, done)
        if done:
            # Episode over for this intersection -- drain the rest of the
            # window too, each remaining entry getting a shorter-than-n
            # return over whatever ticks are actually left. Standard n-step
            # practice: don't bootstrap across an episode boundary, and
            # don't invent extra transitions past it either.
            while buf:
                self._flush_nstep(buf, next_obs, done)

    def _flush_nstep(self, buf: "deque", next_obs: Observation, done: bool) -> None:
        """Pop the oldest entry in an n-step window, compute its return over
        whatever rewards currently sit in the window (already clipped
        per-tick by ``_clip_reward``, so the sum is bounded and doesn't need
        clipping again), and push the resulting multi-step transition into
        the shared replay buffer with n = window length at flush time."""
        obs0, action0, _ = buf[0]
        n = len(buf)
        ret = 0.0
        for i, (_, _, r) in enumerate(buf):
            ret += (self.gamma ** i) * r
        self.replay.add(obs0, action0, ret, next_obs, done, n)
        buf.popleft()

    def train_step(self) -> Optional[float]:
        return self.optimize()

    def optimize(self) -> Optional[float]:
        if len(self.replay) < max(4, self.batch_size):
            return None
        # train(): undoes any .eval() left behind by act_batch/_greedy_action_batch
        # (called every tick before this) -- BatchNorm needs batch statistics,
        # not frozen running stats, during the actual gradient step. No-op
        # when use_batchnorm=False.
        self.q.train()

        obs, actions, rewards, next_obs, dones, ns = self.replay.sample(self.batch_size)

        own, neighbors, neighbor_mask, hop_dist, action_mask = _collate(obs, self.device)
        n_own, n_neighbors, n_neighbor_mask, n_hop_dist, n_action_mask = _collate(next_obs, self.device)

        actions_t = torch.tensor(actions, dtype=torch.int64, device=self.device).unsqueeze(1)
        rewards_t = torch.tensor(rewards, dtype=torch.float32, device=self.device).unsqueeze(1)
        dones_t = torch.tensor(dones, dtype=torch.float32, device=self.device).unsqueeze(1)
        # gamma**n per-sample bootstrap discount -- n=1 for every sample
        # (the n_step<=1 default) makes this exactly `self.gamma`, so
        # optimize()'s math is byte-identical to before n-step support
        # existed unless n_step>1 is actually requested.
        ns_t = torch.tensor(ns, dtype=torch.float32, device=self.device).unsqueeze(1)
        discount_t = torch.full_like(ns_t, self.gamma).pow(ns_t)

        q_values = self.q(own, neighbors, neighbor_mask, hop_dist)
        q_taken = q_values.gather(1, actions_t)

        with torch.no_grad():
            # Double DQN: select next action with the online net, but only
            # among actions valid for that next observation's topology.
            next_q_online = _mask_q(
                self.q(n_own, n_neighbors, n_neighbor_mask, n_hop_dist), n_action_mask
            )
            next_actions = next_q_online.argmax(dim=1, keepdim=True)
            next_q_target = self.q_target(n_own, n_neighbors, n_neighbor_mask, n_hop_dist).gather(
                1, next_actions
            )
            expected = rewards_t + (1.0 - dones_t) * discount_t * next_q_target

        # Huber loss instead of MSE: MSE squares the TD-error, so a single
        # large-magnitude transition (e.g. a congestion spike) can
        # dominate the whole gradient step -- that's what was driving
        # city_2's loss climbing into the double digits. Huber is linear
        # past `delta`, so outliers contribute a bounded gradient instead
        # of an exploding one.
        loss = nn.functional.smooth_l1_loss(q_taken, expected, beta=1.0)

        # FedProx proximal term: penalizes this client's weights drifting
        # from the global weights it started the round from. Directly
        # targets client drift in weight-space -- confirmed as a real,
        # reproducible cause of federated instability (city_1 alone trains
        # cleanly; the same seed federated with just one other city swings
        # wildly between near-optimal and catastrophic every few rounds --
        # see fidings/divergence_investigation.md §13). mu=0 recovers
        # plain local training exactly (no-op, not just numerically small).
        if self.q_entropy_weight > 0:
            # Entropy of softmax(Q/1.0) over each sample's VALID actions only
            # -- masked actions get -inf Q (via _mask_q) so softmax already
            # assigns them exactly 0 probability; clamp before log() so those
            # zero-probability terms contribute 0, not nan, to the sum.
            q_masked_for_entropy = _mask_q(q_values, action_mask)
            probs = torch.softmax(q_masked_for_entropy, dim=1)
            entropy = -(probs * torch.log(probs.clamp_min(1e-12))).sum(dim=1)
            loss = loss - self.q_entropy_weight * entropy.mean()

        if self.mu > 0 and self._global_params is not None:
            # Fused multi-tensor ops instead of a Python loop doing one
            # subtract+pow+sum (and one kernel launch) per parameter tensor
            # -- this runs every optimize() call, i.e. every gradient step,
            # so the per-tensor Python/kernel-launch overhead isn't free.
            diffs = torch._foreach_sub(list(self.q.parameters()), self._global_params)
            norms = torch._foreach_norm(diffs, 2)
            prox_term = sum(n.pow(2) for n in norms)
            loss = loss + (self.mu / 2.0) * prox_term

        self.optimizer.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(self.q.parameters(), 10.0)
        self.optimizer.step()
        self.learn_steps += 1
        if self.tau > 0:
            # Polyak (soft) update: target = (1-tau)*target + tau*online
            # Applied every step with small tau so the target drifts
            # smoothly instead of snapping every target_update steps.
            for p, pt in zip(self.q.parameters(), self.q_target.parameters()):
                pt.data.mul_(1.0 - self.tau).add_(self.tau * p.data)
        elif self.learn_steps % self.target_update == 0:
            # Legacy hard copy: kept for ablation (pass tau=0 to enable).
            self.q_target.load_state_dict(self.q.state_dict())
            self.q_target.eval()  # load_state_dict() doesn't touch train/eval mode

        if self.anchor_revert:
            # Reuses q_values/action_mask already computed above for the TD loss --
            # no extra forward pass. See __init__'s comment for the full design.
            self._track_qgap_and_maybe_revert(q_values, action_mask)

        return float(loss.item())

    # ------------------------------------------------------------------
    # Self-Anchoring Training with Confidence-Gated Reversion
    # ------------------------------------------------------------------

    def _track_qgap_and_maybe_revert(self, q_values: "torch.Tensor", action_mask: "torch.Tensor") -> None:
        with torch.no_grad():
            masked = _mask_q(q_values, action_mask)
            if masked.shape[1] < 2:
                return
            top2 = torch.topk(masked, k=2, dim=1).values
            gaps = top2[:, 0] - top2[:, 1]
            finite = gaps[torch.isfinite(gaps)]
            if finite.numel() == 0:
                return
            batch_qgap = float(finite.mean().item())

        self._anchor_optimize_calls += 1
        decay = 0.05
        if self._recent_qgap_ema is None:
            self._recent_qgap_ema = batch_qgap
        else:
            self._recent_qgap_ema = (1.0 - decay) * self._recent_qgap_ema + decay * batch_qgap

        if self._anchor_qgap_ema is None:
            # Still in the warm-up window that establishes THIS round's baseline
            # Q-gap -- don't check for reversion until it's frozen.
            if self._anchor_optimize_calls >= self.anchor_warmup_calls:
                self._anchor_qgap_ema = self._recent_qgap_ema
            return

        if self._anchor_optimize_calls % self.anchor_check_every != 0:
            return

        if (
            self._anchor_qgap_ema > 1e-8
            and self._recent_qgap_ema > self.anchor_qgap_growth_threshold * self._anchor_qgap_ema
            and self._anchor_state is not None
        ):
            self._apply_anchor_pullback()

    def _apply_anchor_pullback(self) -> None:
        """Blend current weights partway back toward this round's start-of-round
        anchor -- a partial pull-back, not a hard reset, so local training doesn't
        lose all forward progress even while resisting the confident-lock-in slide
        the Q-gap growth just signaled."""
        beta = self.anchor_pullback_beta
        current = self.q.state_dict()
        blended = {
            k: beta * self._anchor_state[k].to(current[k].device, current[k].dtype) + (1.0 - beta) * current[k]
            for k in current
        }
        self.q.load_state_dict(blended)
        logger.info(
            "Anchor-revert pullback: recent Q-gap %.4f exceeded %.1fx this round's "
            "baseline %.4f -- blended %.0f%% back toward round-start weights.",
            self._recent_qgap_ema, self.anchor_qgap_growth_threshold, self._anchor_qgap_ema,
            beta * 100,
        )
        # Reset tracking off the post-pullback state so the same spike doesn't
        # immediately re-trigger before the network has had a chance to move.
        self._recent_qgap_ema = self._anchor_qgap_ema

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def decay_lr(self) -> float:
        """Multiply the optimizer's LR by ``lr_decay``, floored at ``min_lr``.

        Call once per federated round (not per gradient step) -- e.g. from
        the client after ``train()`` returns, or from the server after
        aggregation. A per-city ``lr_decay`` close to 1.0 keeps the rate
        essentially fixed; a value like 0.97 gives a gentle exponential
        decay so a noisy, small city's updates get progressively gentler
        as training proceeds, without needing a fixed schedule length.
        Returns the new LR for logging.
        """
        for group in self.optimizer.param_groups:
            new_lr = max(group["lr"] * self.lr_decay, self.min_lr)
            group["lr"] = new_lr
        return self.optimizer.param_groups[0]["lr"]

    def save(self, path: str) -> None:
        torch.save(self.q.state_dict(), path)

    def load(self, path: str) -> None:
        state = torch.load(path, map_location=self.device)
        self.q.load_state_dict(state)
        self.q_target.load_state_dict(state)
        self.q_target.eval()

    def state_dict(self) -> Dict[str, "torch.Tensor"]:
        return {k: v.cpu() for k, v in self.q.state_dict().items()}

    def load_state_dict(self, state: Dict[str, "torch.Tensor"]) -> None:
        self.q.load_state_dict(state)
        self.q_target.load_state_dict(state)
        self.q_target.eval()

    def start_round(self, global_state: Dict[str, "torch.Tensor"]) -> None:
        """Sync to the broadcast global weights and anchor FedProx's
        proximal reference there, in one call.

        Deliberately separate from plain `load_state_dict()`: that method
        is used elsewhere (e.g. checkpoint restore) where resetting the
        FedProx reference point would be a surprising side effect, not an
        intended "a new federated round is starting" signal.
        """
        self.load_state_dict(global_state)
        if self.mu > 0:
            self._global_params = [p.detach().clone() for p in self.q.parameters()]

    def _on_episode_start(self) -> None:
        """Hook called once per episode by ``train()``, right where n-step
        accumulators are reset -- a no-op here. ``RecurrentDQNAgent``
        overrides this to reset its per-intersection hidden state, so
        ``train()`` itself doesn't need to know anything about recurrence."""
        pass

    def clear_replay(self) -> None:
        """See ReplayBuffer.clear()'s docstring. Also clears any in-flight
        n-step accumulator windows -- a partially-built n-step return
        spanning the reset boundary would otherwise mix pre- and post-reset
        experience into one transition."""
        self.replay.clear()
        self._nstep_buffers = {}

    # ------------------------------------------------------------------
    # Training loop -- multi-agent aware
    # ------------------------------------------------------------------

    def train(
        self,
        env,
        episodes: int = 5,
        log_loss_every_steps: int = 50,
    ) -> Tuple[Dict[str, "torch.Tensor"], int]:
        """Train against a multi-agent city environment.

        Contract expected of ``env``:
            env.reset()            -> Dict[ts_id, obs_dict]
            env.step(actions)      -> (Dict[ts_id, obs_dict],
                                        Dict[ts_id, float] rewards,
                                        Dict[ts_id, bool] dones (may
                                            include "__all__"),
                                        info dict)

        Every intersection in the city is stepped simultaneously each
        tick, using the SAME shared network to pick each intersection's
        action; every intersection's transition is stored in the same
        replay buffer.
        """
        total_steps = 0
        all_losses: List[float] = []   # across every episode this call
        action_counts: Counter = Counter()   # {action_index: times_taken}, this call

        if self.anchor_revert:
            # Fresh anchor every train() call (= every federated round, or every
            # solo-training call for the diagnostic scripts) -- deliberately NOT
            # carried across calls, so this has no cross-round state to reason
            # about (no interaction with aggregation, --resume, etc.). See
            # __init__'s comment for the full design.
            self._anchor_state = {k: v.detach().clone() for k, v in self.q.state_dict().items()}
            self._anchor_qgap_ema = None
            self._recent_qgap_ema = None
            self._anchor_optimize_calls = 0

        for ep in range(1, episodes + 1):
            obs_dict = env.reset()
            if not isinstance(obs_dict, dict):
                # Backward-compat: single-agent env returning a flat obs.
                obs_dict = {"__single__": obs_dict}
            # Fresh n-step windows each episode -- ticks from a finished
            # episode should never bleed a bootstrap target into the next
            # one. A no-op when n_step<=1 (buffers stay unused).
            self._nstep_buffers = {}
            self._on_episode_start()

            done = False
            ep_steps = 0
            ep_losses: List[float] = []

            while not done:
                # One shared epsilon for this tick, used by every
                # intersection -- see _current_epsilon's docstring for
                # why this must NOT be per-intersection.
                eps = self._current_epsilon()
                actions = self.act_batch(obs_dict, eps=eps, explore=True)
                self.steps_done += 1
                action_counts.update(actions.values())

                if len(actions) == 1 and "__single__" in actions:
                    next_obs, reward, done, _ = env.step(actions["__single__"])
                    next_obs_dict = {"__single__": next_obs}
                    rewards = {"__single__": reward}
                    dones = {"__single__": done, "__all__": done}
                else:
                    next_obs_dict, rewards, dones, _ = env.step(actions)

                for ts_id, o in obs_dict.items():
                    r = rewards.get(ts_id, 0.0)
                    no = next_obs_dict.get(ts_id, o)
                    d = dones.get(ts_id, dones.get("__all__", False))
                    self._remember_step(ts_id, o, actions[ts_id], r, no, d)

                loss = self.optimize()
                if loss is not None:
                    ep_losses.append(loss)
                    all_losses.append(loss)

                obs_dict = next_obs_dict
                done = dones.get("__all__", all(dones.values()) if dones else True)
                ep_steps += 1
                total_steps += 1

                if log_loss_every_steps > 0 and ep_losses and ep_steps % log_loss_every_steps == 0:
                    window = ep_losses[-log_loss_every_steps:]
                    msg = (
                        f"  [train] ep={ep}/{episodes}  step={ep_steps}"
                        f"  loss(last {len(window)})={np.mean(window):.6f}"
                    )
                    logger.info(msg)

            if ep_losses:
                msg = (
                    f"[train] ep={ep}/{episodes}  steps={ep_steps}"
                    f"  loss  mean={np.mean(ep_losses):.6f}"
                    f"  min={np.min(ep_losses):.6f}"
                    f"  max={np.max(ep_losses):.6f}"
                    f"  updates={len(ep_losses)}"
                )
            else:
                msg = f"[train] ep={ep}/{episodes}  steps={ep_steps}  loss=n/a (buffer not yet full)"
            logger.info(msg)

        # Mean loss across every gradient step this call -- forwarded by
        # FederatedClient/CityClient to the server so aggregation strategies
        # that need a loss signal (EMA-based ones) have real data instead
        # of None every round.
        mean_loss = float(np.mean(all_losses)) if all_losses else None
        # Plain dict, not Counter -- keeps it picklable/simple across the
        # process boundary in the parallel path.
        return self.state_dict(), total_steps, mean_loss, dict(action_counts)
